"""Initial migration

Revision ID: 429d88fe997f
Revises: 
Create Date: 2025-04-11 00:01:35.064157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429d88fe997f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('properties',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('LIST', 'INT', name='propertytype'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('property_values',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('property_uid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['property_uid'], ['properties.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('product_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_uid', sa.String(), nullable=False),
    sa.Column('property_uid', sa.String(), nullable=False),
    sa.Column('value_uid', sa.String(), nullable=True),
    sa.Column('int_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_uid'], ['products.uid'], ),
    sa.ForeignKeyConstraint(['property_uid'], ['properties.uid'], ),
    sa.ForeignKeyConstraint(['value_uid'], ['property_values.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_properties')
    op.drop_table('property_values')
    op.drop_table('properties')
    op.drop_table('products')
    # ### end Alembic commands ###
